# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pavel/Документы/cw-iv-021_todo-list

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pavel/Документы/cw-iv-021_todo-list

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pavel/Документы/cw-iv-021_todo-list/CMakeFiles /home/pavel/Документы/cw-iv-021_todo-list/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pavel/Документы/cw-iv-021_todo-list/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MainMenu

# Build rule for target.
MainMenu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MainMenu
.PHONY : MainMenu

# fast build rule for target.
MainMenu/fast:
	$(MAKE) -f ToDo/CMakeFiles/MainMenu.dir/build.make ToDo/CMakeFiles/MainMenu.dir/build
.PHONY : MainMenu/fast

#=============================================================================
# Target rules for targets named MainMenu_autogen

# Build rule for target.
MainMenu_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MainMenu_autogen
.PHONY : MainMenu_autogen

# fast build rule for target.
MainMenu_autogen/fast:
	$(MAKE) -f ToDo/CMakeFiles/MainMenu_autogen.dir/build.make ToDo/CMakeFiles/MainMenu_autogen.dir/build
.PHONY : MainMenu_autogen/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named tests_autogen

# Build rule for target.
tests_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests_autogen
.PHONY : tests_autogen

# fast build rule for target.
tests_autogen/fast:
	$(MAKE) -f tests/CMakeFiles/tests_autogen.dir/build.make tests/CMakeFiles/tests_autogen.dir/build
.PHONY : tests_autogen/fast

#=============================================================================
# Target rules for targets named libToDo

# Build rule for target.
libToDo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libToDo
.PHONY : libToDo

# fast build rule for target.
libToDo/fast:
	$(MAKE) -f ToDoFile/CMakeFiles/libToDo.dir/build.make ToDoFile/CMakeFiles/libToDo.dir/build
.PHONY : libToDo/fast

#=============================================================================
# Target rules for targets named libToDo_autogen

# Build rule for target.
libToDo_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libToDo_autogen
.PHONY : libToDo_autogen

# fast build rule for target.
libToDo_autogen/fast:
	$(MAKE) -f ToDoFile/CMakeFiles/libToDo_autogen.dir/build.make ToDoFile/CMakeFiles/libToDo_autogen.dir/build
.PHONY : libToDo_autogen/fast

#=============================================================================
# Target rules for targets named qtcsv

# Build rule for target.
qtcsv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qtcsv
.PHONY : qtcsv

# fast build rule for target.
qtcsv/fast:
	$(MAKE) -f ToDoFile/thirdparty/qtcsv/CMakeFiles/qtcsv.dir/build.make ToDoFile/thirdparty/qtcsv/CMakeFiles/qtcsv.dir/build
.PHONY : qtcsv/fast

#=============================================================================
# Target rules for targets named qtcsv_autogen

# Build rule for target.
qtcsv_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qtcsv_autogen
.PHONY : qtcsv_autogen

# fast build rule for target.
qtcsv_autogen/fast:
	$(MAKE) -f ToDoFile/thirdparty/qtcsv/CMakeFiles/qtcsv_autogen.dir/build.make ToDoFile/thirdparty/qtcsv/CMakeFiles/qtcsv_autogen.dir/build
.PHONY : qtcsv_autogen/fast

#=============================================================================
# Target rules for targets named qtcsv_tests

# Build rule for target.
qtcsv_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qtcsv_tests
.PHONY : qtcsv_tests

# fast build rule for target.
qtcsv_tests/fast:
	$(MAKE) -f ToDoFile/thirdparty/qtcsv/tests/CMakeFiles/qtcsv_tests.dir/build.make ToDoFile/thirdparty/qtcsv/tests/CMakeFiles/qtcsv_tests.dir/build
.PHONY : qtcsv_tests/fast

#=============================================================================
# Target rules for targets named qtcsv_tests_autogen

# Build rule for target.
qtcsv_tests_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qtcsv_tests_autogen
.PHONY : qtcsv_tests_autogen

# fast build rule for target.
qtcsv_tests_autogen/fast:
	$(MAKE) -f ToDoFile/thirdparty/qtcsv/tests/CMakeFiles/qtcsv_tests_autogen.dir/build.make ToDoFile/thirdparty/qtcsv/tests/CMakeFiles/qtcsv_tests_autogen.dir/build
.PHONY : qtcsv_tests_autogen/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... MainMenu"
	@echo "... MainMenu_autogen"
	@echo "... tests"
	@echo "... tests_autogen"
	@echo "... libToDo"
	@echo "... libToDo_autogen"
	@echo "... qtcsv"
	@echo "... qtcsv_autogen"
	@echo "... qtcsv_tests"
	@echo "... qtcsv_tests_autogen"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

