name: CMake

on:
  push:
    branches: [ issue7 ]
  pull_request:
    branches: [ issue7 ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: Configure Qt
      run:   sudo apt install qt5-default && sudo apt install qtcreator

    - name: Build
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ${{github.workspace}} && cmake --build .
    - name: Run
      run: cmake -E copy base.csv build/tests && cd build && cd tests && ./tests
